### ISSUE TITLE
Problems with FHoSS using wrong OPc

### ISSUE THREAD

**Issue by laf0rge** [herlesupreeth/FHoSS#4]
Hi @herlesupreeth, I've been catching up with a lot of your great work, thanks for releasing all of this.

I'm running into problems with FHoSS and your OPc support, however.

Even though the web UI shows all-zero OP and the correct OPc, FHoSS uses a wrong OPc value for computation (as seen in the logs)

![fhoss-web](https://user-images.githubusercontent.com/1250205/133679479-e912ef0c-e137-4902-af8a-c15d2f318220.png)

![fhoss-log](https://user-images.githubusercontent.com/1250205/133679497-05f8897e-795d-4dc7-bcbc-3cfdca605532.png)

The result is of course that all IMS authentication fails.  I have this issue with all of the subscribers I created, despite the web-ui showing the  correct OPc, always a wrong value is used during computation of the quintuples for IMS AKA.

**Comment by laf0rge** [comment]
Intererstingly, the database is storing the correct value (as in the UI):
```
mysql> select identity,k,op,opc from impi;
+---------------------------------------------------+------------------------------------+------------------------------------+------------------------------------+
| identity                                          | k                                  | op                                 | opc                                |
+---------------------------------------------------+------------------------------------+------------------------------------+------------------------------------+
| 001010000053004@ims.mnc001.mcc001.3gppnetwork.org | 0xCE57888A8416BBDE4119DCA92CBE167B | 0x00000000000000000000000000000000 | 0x22B3156098E11E177E93711D6CB0E688 |
+---------------------------------------------------+------------------------------------+------------------------------------+------------------------------------+
```

So UI and DB agree, but why is it using something completely else when performing the MAR/MAA...

**Comment by laf0rge** [comment]
Ok, so if I manually perform the OPc generation from an OP value of 22B3156098E11E177E93711D6CB0E688 and the K value of CE57888A8416BBDE4119DCA92CBE167B I am getting the A38C1B13F1543EAD404B98C247BC0452 value that FHoSS is using in its computation.  So somehow it is using the value from the OPc column but treating it as OP!

**Comment by laf0rge** [comment]
I read the code like 10 times by now, but I really cannot find how the opc column would be treated as op.  WTF is happening here...
I'm using master of your FHoSS, built two days ago, via docker_open5gs.

**Comment by laf0rge** [comment]
> Ok, so if I manually perform the OPc generation from an OP value of 22B3156098E11E177E93711D6CB0E688 and the K value of CE57888A8416BBDE4119DCA92CBE167B I am getting the A38C1B13F1543EAD404B98C247BC0452 value that FHoSS is using in its computation. So somehow it is using the value from the OPc column but treating it as OP!

Not sure what I did last night while tired, but today I'm not getting that result.  OPc derivation of OP+K in the above example is 4D7F80504E395B082B0E73AFE55D3E69 - so the questions is where does FHoSS get that a38c1b13f1543ead404b98c247bc0452 from, which is not stored anywhere.

**Comment by laf0rge** [comment]
ok, so with tons of additional print statements, I am now at a point where I can pinpoint where things go wrong - but not yet why.

The check `HexCodec.encode(impi.getOp()) == HSSProperties.OPERATOR_ID` evaluatest to false, but if I print both, they render an equal-length string of zeroes:
```
fhoss        | [Thread-11] INFO  de.fhg.fokus.hss.cx.op.MAR  - impi.OP:00000000000000000000000000000000
fhoss        | [Thread-11] INFO  de.fhg.fokus.hss.cx.op.MAR  - Properties.OPERATOR_ID:00000000000000000000000000000000
```
yet the if statement clearly takes the "is not equal" path.

Guess I'll have to read up on Java string comparison [I have zero clue about java]

**Comment by laf0rge** [comment]
I guess somebody else writing that code (hint...) also has as much knowledge about Java as I do :)

See  https://www.javatpoint.com/string-comparison-in-java

The '==' operator compares references, not the content.  So it's like in C comparing pointers vs. strcmp actually comparing the content of the strings.  Obviously, when the sequence of zeroes is read from the SQL database it is not a reference to the property, but a different string with the same content.

**Comment by herlesupreeth** [comment]
@laf0rge wonderful catch. Thank you for the fix
