### ISSUE TITLE
problem with creating new user in FoHSS

### ISSUE THREAD

**Issue by aniee01** [herlesupreeth/FHoSS#6]
hi @herlesupreeth,
 I am facing issue regarding new users in FoHSS. I have ubuntu 18 on my VM and did all the steps in the guide https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/ . my Pcrf is connecting with pcscf, and FoHSS is showing connection with scscf and icscf. 
But when i open my FoHSS console i got following page 

![Screenshot from 2023-09-05 11-16-31](https://github.com/herlesupreeth/FHoSS/assets/77288953/5fe5049c-963d-46a2-be4f-a91ec102b4eb)
 I am not sure , why this is happening. i cant create anything in FoHSS , i only have the search option but not create. kindly guide me in this matter.

Regards

**Comment by herlesupreeth** [comment]
Kindly restart FHoSS and send the logs please

**Comment by aniee01** [comment]
[system_logs.zip](https://github.com/herlesupreeth/FHoSS/files/12527218/system_logs.zip)
 these are the logs of system.

**Comment by herlesupreeth** [comment]
I dont see FHoSS logs in the logs you attached. I need the FHoSS logs not kamailio logs.

**Comment by aniee01** [comment]
[fohss _logs.tar.gz](https://github.com/herlesupreeth/FHoSS/files/12535481/fohss._logs.tar.gz)
I apologies for misunderstanding the words. here are the logs of fohss that i received in linux terminal.

**Comment by herlesupreeth** [comment]
Thanks for the logs. I see the following in FhoSS logs

```
[main] INFO  org.apache.coyote.http11.Http11Protocol  - Initializing Coyote HTTP/1.1 on http-192.168.1.50-8080
[main] INFO  org.apache.coyote.http11.Http11Protocol  - Starting Coyote HTTP/1.1 on http-192.168.1.50-8080
[main] WARN  org.apache.catalina.connector.MapperListener  - Unknown default host: 192.168.1.50
```

and also

`hibernate.connection.url=jdbc:mysql://127.0.0.1:3306/hss_db`

I remember writing the guide to change the above URL. So I would suggest to re-read each step of configuration as its a configuration issue.

**Comment by aniee01** [comment]
its working now. Thank you
