### ISSUE TITLE
 Could not find or load main class org.apache.tools.ant.launch.Launcher

### ISSUE THREAD

**Issue by faratell** [herlesupreeth/FHoSS#7]
Hello.
I have this error when try to compile:
sudo ant compile deploy --execdebug| sudo tee ant_compile_deploy.txt
exec "$JAVACMD"  -classpath "$LOCALCLASSPATH" -Dant.home="$ANT_HOME" -Dant.library.dir="$ANT_LIB"  org.apache.tools.ant.launch.Launcher  -cp "$CLASSPATH"  "compile" "deploy"
Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Launcher

*******************************************************
sudo  update-alternatives --display java
[sudo] password for faraz: 
java - auto mode
  link best version is /usr/lib/jvm/jdk-21.0.2/bin/java
  link currently points to /usr/lib/jvm/jdk-21.0.2/bin/java
  link java is /usr/bin/java
/usr/lib/jvm/jdk-21.0.2/bin/java - priority 100
*******************************************************
ant -version
Apache Ant(TM) version 1.10.14 compiled on August 16 2023

and ant is installed in /usr/local/apache-ant-1.10.14
************************************************************
and I also set:
export JAVACMD="/usr/lib/jvm/jdk-21.0.2"
export LOCALCLASSPATH="/usr/lib/jvm/jdk-21.0.2/lib"
export ANT_HOME="/usr/local/apache-ant-1.10.14"
export ANT_LIB="/usr/local/apache-ant-1.10.14/lib"
export CLASSPATH="/usr/lib/jvm/jdk-21.0.2/lib/"

can help me to solve this error?

**Comment by herlesupreeth** [comment]
Please try compiling with Apache Ant(TM) version 1.9.14 compiled on March 12 2019 version

NOTE: I no longer recommend using FHoSS since the libraries it uses are no longer available/supported in latest Ubuntu releases so I would recommend using pyHSS as the IMS HSS. I havent had time to update the open5gs tutorial so in coming days I will update the tutorial to use pyHSS.

**Comment by faratell** [comment]
thank you for your reply.
I use Ant 1.9.14 and java 1.7.0_80 and also run as root user (not sudo). My problem is solved. I already use ubuntu 22.04, and install FHOSS. Will there be a problem?

**Comment by herlesupreeth** [comment]
I havent tested it by installing on Ubuntu 22.04 so cant say for sure but if it installs fine it should be okay

**Comment by faratell** [comment]
I have installed opn5gs from package manager and change all confiduration like what say in :
https://github.com/herlesupreeth/Open5gs_Config
FoHSS  deploy fine. But when i run hss.sh have this error:
./hss.sh
Building Classpath
Classpath is lib/xml-apis.jar:lib/xercesImpl.jar:lib/xerces-2.4.0.jar:lib/xalan-2.4.0.jar:lib/tomcat-util.jar:lib/tomcat-http.jar:lib/tomcat-coyote.jar:lib/struts.jar:lib/servlets-default.jar:lib/servlet-api.jar:lib/naming-resources.jar:lib/naming-factory.jar:lib/mysql-connector-java-5.1.49-bin.jar:lib/mx4j-3.0.1.jar:lib/log4j.jar:lib/junit.jar:lib/junitee.jar:lib/jta.jar:lib/jsp-api.jar:lib/jmx.jar:lib/jdp.jar:lib/jasper-runtime.jar:lib/jasper-compiler-jdt.jar:lib/jasper-compiler.jar:lib/hibernate3.jar:lib/FHoSS.jar:lib/ehcache-1.1.jar:lib/dom4j-1.6.1.jar:lib/commons-validator.jar:lib/commons-modeler.jar:lib/commons-logging.jar:lib/commons-logging-1.0.4.jar:lib/commons-lang.jar:lib/commons-fileupload.jar:lib/commons-el.jar:lib/commons-digester.jar:lib/commons-collections-3.1.jar:lib/commons-beanutils.jar:lib/cglib-2.1.3.jar:lib/catalina-optional.jar:lib/catalina.jar:lib/c3p0-0.9.1.jar:lib/base64.jar:lib/asm.jar:lib/asm-attrs.jar:lib/antlr-2.7.6.jar:/usr/lib/jvm/jdk1.7.0_80/jre/lib/:log4j.properties:..
[main] INFO  de.fhg.fokus.hss.main.TomcatServer  - Tomcat-Server is started.
[main] INFO  org.apache.catalina.startup.Embedded  - Starting tomcat server
[main] INFO  org.apache.catalina.core.StandardEngine  - Starting Servlet Engine: Apache Tomcat/5.5.9
[main] ERROR org.apache.coyote.http11.Http11Protocol  - Error initializing endpoint
java.net.BindException: Cannot assign requested address:8080
	at org.apache.tomcat.util.net.PoolTcpEndpoint.initEndpoint(PoolTcpEndpoint.java:297)
	at org.apache.coyote.http11.Http11Protocol.init(Http11Protocol.java:142)
	at org.apache.catalina.connector.Connector.initialize(Connector.java:928)
	at org.apache.catalina.startup.Embedded.start(Embedded.java:794)
	at de.fhg.fokus.hss.main.TomcatServer.startTomcat(TomcatServer.java:128)
	at de.fhg.fokus.hss.main.HSSContainer.<init>(HSSContainer.java:74)
	at de.fhg.fokus.hss.main.HSSContainer.main(HSSContainer.java:110)
[main] ERROR de.fhg.fokus.hss.main.HSSContainer  - Exception occured during starting Tomcat!
Exiting from HSS...
LifecycleException:  Protocol handler initialization failed: java.net.BindException: Cannot assign requested address:8080
	at org.apache.catalina.connector.Connector.initialize(Connector.java:930)
	at org.apache.catalina.startup.Embedded.start(Embedded.java:794)
	at de.fhg.fokus.hss.main.TomcatServer.startTomcat(TomcatServer.java:128)
	at de.fhg.fokus.hss.main.HSSContainer.<init>(HSSContainer.java:74)
	at de.fhg.fokus.hss.main.HSSContainer.main(HSSContainer.java:110)

**Comment by herlesupreeth** [comment]
> LifecycleException: Protocol handler initialization failed: java.net.BindException: Cannot assign requested address:8080

This means the IP address configured in FHoSS for Tomcat is incorrect

> I have installed opn5gs from package manager and change all confiduration like what say in :
> https://github.com/herlesupreeth/Open5gs_Config

I think those configs cant be used with latest open5gs tag ..maybe valid for tag 2.6.x

**Comment by faratell** [comment]
Thanks for your reply.
Are you propose me to uninstall open5gs and reinstall it from this link?
https://open5gs.org/open5gs/docs/guide/02-building-open5gs-from-sources/
if i flow it the open5gs 2.6 will be installed?

**Comment by herlesupreeth** [comment]
> Are you propose me to uninstall open5gs and reinstall it from this link?
> https://open5gs.org/open5gs/docs/guide/02-building-open5gs-from-sources/
> if i flow it the open5gs 2.6 will be installed?

After you do git clone you would have to do `cd open5gs && git checkout tags/v2.6.6`

**Comment by faratell** [comment]
There are two branches available in https://github.com/open5gs/open5gs/branches sec and main. 
what is your purpose?

**Comment by herlesupreeth** [comment]
If you do git clone open5gs repo it will fetch main branch which is at tag 2.7.0 and the configuration files in Open5gs_Config will not be relevant anymore so when you do cd open5gs && git checkout tags/v2.6.6 it will fetch the code at tag v2.6.6

**Comment by faratell** [comment]
I am trying to install open5gs tags/v2.6.6 on ubuntu 18.04. when i run ./build/tests/attach/attach have this error:
01/29 14:51:19.185: [diam] ERROR: pid:Main in [fd_sctp_create_bind_server@sctp.c](mailto:fd_sctp_create_bind_server@sctp.c):883: ERROR: in '(sctp_bindx(*sock, sar, count, 0x01))' : Address already in use
((null):0)
01/29 14:51:19.185: [diam] ERROR: pid:Main in [fd_cnx_serv_sctp@cnxctx.c](mailto:fd_cnx_serv_sctp@cnxctx.c):181: ERROR: in '(fd_sctp_create_bind_server( &cnx->cc_socket, cnx->cc_family, ep_list, port ))' : Address already in use
((null):0)
01/29 14:51:19.185: [diam] ERROR: pid:Main in [fd_servers_start@server.c](mailto:fd_servers_start@server.c):355: ERROR: in '(s->conn = fd_cnx_serv_sctp(fd_g_config->cnf_port, empty_conf_ep ? ((void *)0) : &fd_g_config->cnf_endpoints))' : Transport endpoint is not connected
((null):0)
01/29 14:51:19.185: [diam] ERROR: pid:Main in [fd_core_start_int@core.c](mailto:fd_core_start_int@core.c):300: ERROR: in '((fd_servers_start()))' : Transport endpoint is not connected
((null):0)
01/29 14:51:19.185: [diam] ERROR: pid:Main in [ogs_diam_start@init.c](mailto:ogs_diam_start@init.c):71: ERROR: in '(fd_core_start())' : Transport endpoint is not connected
((null):0)
01/29 14:51:19.233: [diam] ERROR: pid:Main in [fd_sctp_create_bind_server@sctp.c](mailto:fd_sctp_create_bind_server@sctp.c):883: ERROR: in '(sctp_bindx(*sock, sar, count, 0x01))' : Address already in use
((null):0)
01/29 14:51:19.233: [diam] ERROR: pid:Main in [fd_cnx_serv_sctp@cnxctx.c](mailto:fd_cnx_serv_sctp@cnxctx.c):181: ERROR: in '(fd_sctp_create_bind_server( &cnx->cc_socket, cnx->cc_family, ep_list, port ))' : Address already in use
((null):0)
01/29 14:51:19.233: [diam] ERROR: pid:Main in [fd_servers_start@server.c](mailto:fd_servers_start@server.c):355: ERROR: in '(s->conn = fd_cnx_serv_sctp(fd_g_config->cnf_port, empty_conf_ep ? ((void *)0) : &fd_g_config->cnf_endpoints))' : Transport endpoint is not connected
((null):0)
01/29 14:51:19.233: [diam] ERROR: pid:Main in [fd_core_start_int@core.c](mailto:fd_core_start_int@core.c):300: ERROR: in '((fd_servers_start()))' : Transport endpoint is not connected
((null):0)
01/29 14:51:19.233: [diam] ERROR: pid:Main in [ogs_diam_start@init.c](mailto:ogs_diam_start@init.c):71: ERROR: in '(fd_core_start())' : Transport endpoint is not connected
((null):0)
01/29 14:51:19.293: [hss] FATAL: hss_fd_init: Assertion rv == 0&apos; failed. (../src/hss/hss-fd-path.c:41) <font color="#4E9A06">01/29 14:51:19.293</font>: [<font color="#C4A000">core</font>] <font color="#EF2929"><b>FATAL</b></font>: backtrace() returned 7 addresses (../lib/core/ogs-abort.c:37) /home/ubuntu/open5gs/build/src/hss/open5gs-hssd(+0x19851) [0x5580b790d851] /home/ubuntu/open5gs/build/src/hss/open5gs-hssd(+0x6ce4) [0x5580b78face4] /home/ubuntu/open5gs/build/src/hss/open5gs-hssd(+0x62eb) [0x5580b78fa2eb] /home/ubuntu/open5gs/build/src/hss/open5gs-hssd(+0x6b6a) [0x5580b78fab6a] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6a86585c87] /home/ubuntu/open5gs/build/src/hss/open5gs-hssd(+0x61fa) [0x5580b78fa1fa] <font color="#4E9A06">01/29 14:51:19.303</font>: [<font color="#C4A000">sock</font>] <font color="#FCE94F"><b>ERROR</b></font>: socket bind(2) [127.0.0.7]:8805 failed (98:Address already in use) (../lib/core/ogs-socket.c:116) <font color="#4E9A06">01/29 14:51:19.303</font>: [<font color="#C4A000">sock</font>] <font color="#FCE94F"><b>ERROR</b></font>: udp_server() [127.0.0.7]:8805 failed (98:Address already in use) (../lib/core/ogs-udp.c:69) <font color="#4E9A06">01/29 14:51:19.303</font>: [<font color="#C4A000">app</font>] <font color="#FCE94F"><b>ERROR</b></font>: Failed to intialize UPF (../src/upf/app.c:28) <font color="#4E9A06">01/29 14:51:19.303</font>: [<font color="#C4A000">app</font>] <font color="#EF2929"><b>FATAL</b></font>: Open5GS initialization failed. Aborted (../src/main.c:219) <font color="#4E9A06">01/29 14:51:19.303</font>: [<font color="#C4A000">core</font>] <font color="#EF2929"><b>FATAL</b></font>: child_main: Assertion out_return_code == 0' failed. (../tests/common/application.c:106)
01/29 14:51:19.304: [core] FATAL: backtrace() returned 5 addresses (../lib/core/ogs-abort.c:37)
./build/tests/attach/attach(+0x33c4e) [0x55f8a821ac4e]
/home/ubuntu/open5gs/build/tests/attach/../../lib/core/libogscore.so.2(+0x105fe) [0x7ff465f8e5fe]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7ff46383a6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7ff46356361f]
Aborted (core dumped)

I checked that no process use these ports:
root@ubuntu:/home/ubuntu/open5gs# netstat -tuln | grep 883
root@ubuntu:/home/ubuntu/open5gs# netstat -tuln | grep 181
root@ubuntu:/home/ubuntu/open5gs# netstat -tuln | grep 355
root@ubuntu:/home/ubuntu/open5gs# netstat -tuln | grep 883
how can solve this?

**Comment by herlesupreeth** [comment]
I would suggest to raise this as an issue in open5gs repo as its related to running the tests and not related to FHoSS.
